# Generated by Django 4.1.4 on 2022-12-15 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название станции')),
                ('condition', models.CharField(choices=[('runing', 'запущена'), ('broken', 'сломана')], default='runing', max_length=10, verbose_name='Состояние')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('broken_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата поломки')),
                ('x', models.IntegerField(default=100)),
                ('y', models.IntegerField(default=100)),
                ('z', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(choices=[('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=1)),
                ('distance', models.IntegerField()),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indication', to='api.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indication', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
