# Generated by Django 4.1.4 on 2022-12-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indication',
            old_name='station_id',
            new_name='station',
        ),
    ]
